import types

test_types = {
    '__main__': {
        'pow': types.BuiltinFunctionType, 
        'fsum': types.BuiltinFunctionType, 
        'cosh': types.BuiltinFunctionType, 
        'ldexp': types.BuiltinFunctionType, 
        'hypot': types.BuiltinFunctionType, 
        'acosh': types.BuiltinFunctionType, 
        'tan': types.BuiltinFunctionType, 
        'asin': types.BuiltinFunctionType, 
        'isnan': types.BuiltinFunctionType, 
        'log': types.BuiltinFunctionType, 
        'fabs': types.BuiltinFunctionType, 
        'floor': types.BuiltinFunctionType, 
        'atanh': types.BuiltinFunctionType, 
        'sqrt': types.BuiltinFunctionType, 
        'frexp': types.BuiltinFunctionType, 
        'factorial': types.BuiltinFunctionType, 
        'degrees': types.BuiltinFunctionType, 
        'pi': float, 
        'log10': types.BuiltinFunctionType, 
        'asinh': types.BuiltinFunctionType, 
        'fmod': types.BuiltinFunctionType, 
        'atan': types.BuiltinFunctionType, 
        'copysign': types.BuiltinFunctionType, 
        'cos': types.BuiltinFunctionType, 
        'ceil': types.BuiltinFunctionType, 
        'TypeDataFileWriter': types.ClassType, 
        'atan2': types.BuiltinFunctionType, 
        'isinf': types.BuiltinFunctionType, 
        'sinh': types.BuiltinFunctionType, 
        'x': float, 
        'trunc': types.BuiltinFunctionType, 
        'expm1': types.BuiltinFunctionType, 
        'e': float, 
        'tanh': types.BuiltinFunctionType, 
        'f': float, 
        'radians': types.BuiltinFunctionType, 
#        'sin': types.BuiltinFunctionType,
        'lgamma': types.BuiltinFunctionType, 
        'erf': types.BuiltinFunctionType, 
        'erfc': types.BuiltinFunctionType, 
        'modf': types.BuiltinFunctionType, 
        'exp': types.BuiltinFunctionType, 
        'acos': types.BuiltinFunctionType, 
        'log1p': types.BuiltinFunctionType, 
        'gamma': types.BuiltinFunctionType, 
    }, 
}
