from testing.code_generation_testing.codegen_testing_common import instance_of_class_name

test_types = {
    '__main__': {
        'r26': instance_of_class_name("ndarray"),
        'r25': instance_of_class_name("tuple"),
        'r24': instance_of_class_name("ndarray"),
        'r23': instance_of_class_name("ndarray"),
        'r22': instance_of_class_name("ndarray"),
        'r21': instance_of_class_name("ndarray"),
        'r20': instance_of_class_name("ndarray"),
        '__package__': instance_of_class_name("NoneType"),
        'np': instance_of_class_name("module"),
        '__doc__': instance_of_class_name("NoneType"),
        'r16': instance_of_class_name("ndarray"),
        'r17': instance_of_class_name("ndarray"),
        'r14': instance_of_class_name("ndarray"),
        'r15': instance_of_class_name("ndarray"),
        'r12': instance_of_class_name("tuple"),
        'r13': instance_of_class_name("float64"),
        'r10': instance_of_class_name("float64"),
        'r11': instance_of_class_name("float64"),
        '__builtins__': instance_of_class_name("module"),
        '__file__': instance_of_class_name("str"),
        'r18': instance_of_class_name("ndarray"),
        'r19': instance_of_class_name("ndarray"),
        'x2': instance_of_class_name("list"),
        '__name__': instance_of_class_name("str"),
        'x1': instance_of_class_name("list"),
        'r4': instance_of_class_name("float64"),
        'r5': instance_of_class_name("float64"),
        'r6': instance_of_class_name("float64"),
        'r7': instance_of_class_name("float64"),
        'r1': instance_of_class_name("float64"),
        'r2': instance_of_class_name("float64"),
        'r3': instance_of_class_name("float64"),
        'r8': instance_of_class_name("float64"),
        'r9': instance_of_class_name("float64"),
        'x': instance_of_class_name("list"),

    },
}
