from stypy.errors.type_error import StypyTypeError
from testing.code_generation_testing.codegen_testing_common import instance_of_class_name

test_types = {
    '__main__': {
        'fp': instance_of_class_name("list"),
        'a_max': instance_of_class_name("int"),
        'a_min': instance_of_class_name("int"),
        'r15': instance_of_class_name("ndarray"),
        'r29': instance_of_class_name("ndarray"),
        'r28': instance_of_class_name("ndarray"),
        'r27': instance_of_class_name("float"),
        'r26': instance_of_class_name("ndarray"),
        'xp': instance_of_class_name("list"),
        'r24': instance_of_class_name("float64"),
        'r23': instance_of_class_name("float64"),
        'r22': instance_of_class_name("float64"),
        'r21': instance_of_class_name("float64"),
        'r20': instance_of_class_name("ndarray"),
        '__package__': instance_of_class_name("NoneType"),
        'np': instance_of_class_name("module"),
        '__doc__': instance_of_class_name("NoneType"),
        'r16': instance_of_class_name("ndarray"),
        'r17': instance_of_class_name("ndarray"),
        'r14': instance_of_class_name("ndarray"),
        'UNDEF': instance_of_class_name("float"),
        'r12': instance_of_class_name("float64"),
        'r13': instance_of_class_name("ndarray"),
        'r10': instance_of_class_name("float64"),
        'r11': instance_of_class_name("float64"),
        '__builtins__': instance_of_class_name("module"),
        '__file__': instance_of_class_name("str"),
        'r18': instance_of_class_name("ndarray"),
        'r19': instance_of_class_name("ndarray"),
        'a': instance_of_class_name("list"),
        'x2': instance_of_class_name("float"),
        '__name__': instance_of_class_name("str"),
        'x1': instance_of_class_name("float"),
        'r30': instance_of_class_name("float"),
        'r25': instance_of_class_name("ndarray"),
        'r4': instance_of_class_name("float64"),
        'r5': instance_of_class_name("float64"),
        'r6': instance_of_class_name("float64"),
        'r7': instance_of_class_name("float64"),
        'r1': instance_of_class_name("ndarray"),
        'r2': instance_of_class_name("float64"),
        'r3': instance_of_class_name("float64"),
        'r8': instance_of_class_name("float64"),
        'r9': instance_of_class_name("float64"),
        'v': instance_of_class_name("float"),
        'x': instance_of_class_name("list"),
        'r14b': StypyTypeError,
    },
}
