# ----------------------------------
# Python error members type rules
# ----------------------------------


import types
from stypy.python_lib.python_types.instantiation.known_python_types_management import ExtraTypeDefinitions
from stypy.python_lib.python_types.type_inference.undefined_type import UndefinedType
from stypy.python_lib.type_rules.type_groups.type_group_generator import *
import os
from os import error



type_rules_of_members = {
    '__setattr__': [
        ((str, tuple), types.NoneType), 
        ((str, enumerate), types.NoneType), 
        ((str, ExtraTypeDefinitions.attrgetter), types.NoneType), 
        ((str, ExtraTypeDefinitions.dictionary_keyiterator), types.NoneType), 
        ((str, types.MethodType), types.NoneType), 
        ((str, ExtraTypeDefinitions.tupleiterator), types.NoneType), 
        ((str, ExtraTypeDefinitions.dictionary_valueiterator), types.NoneType), 
        ((str, frozenset), types.NoneType), 
        ((str, ExtraTypeDefinitions.dictionary_itemiterator), types.NoneType), 
        ((str, ExtraTypeDefinitions.methodcaller), types.NoneType), 
        ((str, int), types.NoneType), 
        ((str, ExtraTypeDefinitions.dict_keys), types.NoneType), 
        ((str, xrange), types.NoneType), 
        ((str, type), types.NoneType), 
        ((str, file), types.NoneType), 
        ((str, types.LambdaType), types.NoneType), 
        ((str, ExtraTypeDefinitions.rangeiterator), types.NoneType), 
        ((str, os.error), types.NoneType), 
        ((str, ExtraTypeDefinitions.callable_iterator), types.NoneType), 
        ((str, slice), types.NoneType), 
        ((str, types.CodeType), types.NoneType), 
        ((str, ExtraTypeDefinitions.dict_values), types.NoneType), 
        ((str, property), types.NoneType), 
        ((str, object), types.NoneType), 
        ((str, bool), types.NoneType), 
        ((str, ExtraTypeDefinitions.formatteriterator), types.NoneType), 
        ((str, ExtraTypeDefinitions.bytearray_iterator), types.NoneType), 
        ((str, long), types.NoneType), 
        ((str, classmethod), types.NoneType), 
        ((str, complex), types.NoneType), 
        ((str, buffer), types.NoneType), 
        ((str, bytearray), types.NoneType), 
        ((str, reversed), types.NoneType), 
        ((str, ExtraTypeDefinitions.listreverseiterator), types.NoneType), 
        ((str, super), types.NoneType), 
        ((str, memoryview), types.NoneType), 
        ((str, staticmethod), types.NoneType), 
        ((str, str), types.NoneType), 
        ((str, types.BuiltinFunctionType), types.NoneType), 
        ((str, ExtraTypeDefinitions.member_descriptor), types.NoneType), 
        ((str, ExtraTypeDefinitions.dict_items), types.NoneType), 
        ((str, types.ClassType), types.NoneType), 
        ((str, list), types.NoneType), 
        ((str, iter), types.NoneType), 
        ((str, ExtraTypeDefinitions.getset_descriptor), types.NoneType), 
        ((str, os._Environ), types.NoneType), 
        ((str, types.ModuleType), types.NoneType), 
        ((str, ExtraTypeDefinitions.listiterator), types.NoneType), 
        ((str, types.GeneratorType), types.NoneType), 
        ((str, ExtraTypeDefinitions.itemgetter), types.NoneType), 
        ((str, types.NoneType), types.NoneType), 
        ((str, set), types.NoneType), 
        ((str, types.InstanceType), types.NoneType), 
        ((str, float), types.NoneType), 
        ((str, unicode), types.NoneType), 
        ((str, types.DictProxyType), types.NoneType), 
        ((str, dict), types.NoneType), 
        ((unicode, tuple), types.NoneType), 
        ((unicode, enumerate), types.NoneType), 
        ((unicode, ExtraTypeDefinitions.attrgetter), types.NoneType), 
        ((unicode, ExtraTypeDefinitions.dictionary_keyiterator), types.NoneType), 
        ((unicode, types.MethodType), types.NoneType), 
        ((unicode, ExtraTypeDefinitions.tupleiterator), types.NoneType), 
        ((unicode, ExtraTypeDefinitions.dictionary_valueiterator), types.NoneType), 
        ((unicode, frozenset), types.NoneType), 
        ((unicode, ExtraTypeDefinitions.dictionary_itemiterator), types.NoneType), 
        ((unicode, ExtraTypeDefinitions.methodcaller), types.NoneType), 
        ((unicode, int), types.NoneType), 
        ((unicode, ExtraTypeDefinitions.dict_keys), types.NoneType), 
        ((unicode, xrange), types.NoneType), 
        ((unicode, type), types.NoneType), 
        ((unicode, file), types.NoneType), 
        ((unicode, types.LambdaType), types.NoneType), 
        ((unicode, ExtraTypeDefinitions.rangeiterator), types.NoneType), 
        ((unicode, os.error), types.NoneType), 
        ((unicode, ExtraTypeDefinitions.callable_iterator), types.NoneType), 
        ((unicode, slice), types.NoneType), 
        ((unicode, types.CodeType), types.NoneType), 
        ((unicode, ExtraTypeDefinitions.dict_values), types.NoneType), 
        ((unicode, property), types.NoneType), 
        ((unicode, object), types.NoneType), 
        ((unicode, bool), types.NoneType), 
        ((unicode, ExtraTypeDefinitions.formatteriterator), types.NoneType), 
        ((unicode, ExtraTypeDefinitions.bytearray_iterator), types.NoneType), 
        ((unicode, long), types.NoneType), 
        ((unicode, classmethod), types.NoneType), 
        ((unicode, complex), types.NoneType), 
        ((unicode, buffer), types.NoneType), 
        ((unicode, bytearray), types.NoneType), 
        ((unicode, reversed), types.NoneType), 
        ((unicode, ExtraTypeDefinitions.listreverseiterator), types.NoneType), 
        ((unicode, super), types.NoneType), 
        ((unicode, memoryview), types.NoneType), 
        ((unicode, staticmethod), types.NoneType), 
        ((unicode, str), types.NoneType), 
        ((unicode, types.BuiltinFunctionType), types.NoneType), 
        ((unicode, ExtraTypeDefinitions.member_descriptor), types.NoneType), 
        ((unicode, ExtraTypeDefinitions.dict_items), types.NoneType), 
        ((unicode, types.ClassType), types.NoneType), 
        ((unicode, list), types.NoneType), 
        ((unicode, iter), types.NoneType), 
        ((unicode, ExtraTypeDefinitions.getset_descriptor), types.NoneType), 
        ((unicode, os._Environ), types.NoneType), 
        ((unicode, types.ModuleType), types.NoneType), 
        ((unicode, ExtraTypeDefinitions.listiterator), types.NoneType), 
        ((unicode, types.GeneratorType), types.NoneType), 
        ((unicode, ExtraTypeDefinitions.itemgetter), types.NoneType), 
        ((unicode, types.NoneType), types.NoneType), 
        ((unicode, set), types.NoneType), 
        ((unicode, types.InstanceType), types.NoneType), 
        ((unicode, float), types.NoneType), 
        ((unicode, unicode), types.NoneType), 
        ((unicode, types.DictProxyType), types.NoneType), 
        ((unicode, dict), types.NoneType), 
    ],
    '__reduce_ex__': [
        ((), tuple), 
        ((int,), tuple), 
        ((bool,), tuple), 
        ((long,), tuple), 
        ((), first_param_has_member('__class__', tuple)), 
        ((), first_param_has_member('__mro__', tuple)), 
        ((types.InstanceType,), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((int,), first_param_has_member('__class__', tuple)), 
        ((bool,), first_param_has_member('__class__', tuple)), 
        ((long,), first_param_has_member('__class__', tuple)), 
        ((int,), first_param_has_member('__mro__', tuple)), 
        ((bool,), first_param_has_member('__mro__', tuple)), 
        ((long,), first_param_has_member('__mro__', tuple)), 
    ],
    '__getitem__': [
        ((bool,), types.InstanceType), 
        ((int,), types.InstanceType), 
        ((long,), types.InstanceType), 
    ],
    '__getslice__': [
        ((int, int), tuple), 
        ((int, bool), tuple), 
        ((int, long), tuple), 
        ((bool, int), tuple), 
        ((bool, bool), tuple), 
        ((bool, long), tuple), 
        ((long, int), tuple), 
        ((long, bool), tuple), 
        ((long, long), tuple), 
        ((int, types.InstanceType), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((bool, types.InstanceType), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((long, types.InstanceType), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, tuple), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, enumerate), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, ExtraTypeDefinitions.attrgetter), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, ExtraTypeDefinitions.dictionary_keyiterator), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, types.MethodType), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, ExtraTypeDefinitions.tupleiterator), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, ExtraTypeDefinitions.dictionary_valueiterator), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, frozenset), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, ExtraTypeDefinitions.dictionary_itemiterator), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, ExtraTypeDefinitions.methodcaller), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, int), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, ExtraTypeDefinitions.dict_keys), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, xrange), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, type), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, file), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, types.LambdaType), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, ExtraTypeDefinitions.rangeiterator), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, os.error), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, ExtraTypeDefinitions.callable_iterator), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, slice), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, types.CodeType), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, ExtraTypeDefinitions.dict_values), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, property), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, object), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, bool), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, ExtraTypeDefinitions.formatteriterator), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, ExtraTypeDefinitions.bytearray_iterator), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, long), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, classmethod), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, complex), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, buffer), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, bytearray), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, reversed), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, ExtraTypeDefinitions.listreverseiterator), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, super), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, memoryview), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, staticmethod), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, str), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, types.BuiltinFunctionType), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, ExtraTypeDefinitions.member_descriptor), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, ExtraTypeDefinitions.dict_items), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, types.ClassType), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, list), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, iter), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, ExtraTypeDefinitions.getset_descriptor), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, os._Environ), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, types.ModuleType), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, ExtraTypeDefinitions.listiterator), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, types.GeneratorType), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, ExtraTypeDefinitions.itemgetter), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, types.NoneType), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, set), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, types.InstanceType), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, float), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, unicode), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, types.DictProxyType), first_instance_type_param_has_member('__trunc__', tuple)), 
        ((types.InstanceType, dict), first_instance_type_param_has_member('__trunc__', tuple)), 
    ],
    '__setstate__': [
        ((os._Environ,), types.NoneType), 
        ((types.NoneType,), types.NoneType), 
        ((dict,), types.NoneType), 
    ],
    '__reduce__': [
        ((), tuple), 
    ],
    '__str__': [
    ],
    '__format__': [
        ((str,), str), 
        ((unicode,), str), 
    ],
    '__getattribute__': [
        ((str,), ABCMeta), 
        ((unicode,), ABCMeta), 
        ((str,), types.NoneType), 
        ((unicode,), types.NoneType), 
    ],
    '__unicode__': [
        ((), unicode), 
    ],
    '__delattr__': [
        ((str,), types.NoneType), 
        ((unicode,), types.NoneType), 
        ((str,), types.NoneType), 
        ((unicode,), types.NoneType), 
    ],
    '__subclasshook__': [
        ((), type), 
    ],
    '__repr__': [
        ((), str), 
    ],
    '__hash__': [
        ((), int), 
    ],
    '__sizeof__': [
        ((), int), 
    ],
    '__init__': [
        ((os.error,), types.NoneType), 
        ((os.error, os.error), types.NoneType), 
        ((os.error, os.error, os.error), types.NoneType), 
        ((os.error, os.error, os.error, os.error), types.NoneType), 
    ],
    '__new__': [
        ((), first_param_is_a_subtype_of('os.error', os.error)), 
        ((os.error,), first_param_is_a_subtype_of('os.error', os.error)), 
    ],
}
