
# -*- coding: utf-8 -*-

"""
ORIGINAL PROGRAM SOURCE CODE:
1: # This file is generated by C:\projects\windows-wheel-builder\numpy\setup.py
2: # It contains system_info results at the time of building this package.
3: __all__ = ["get_info","show"]
4: 
5: atlas_3_10_blas_threads_info={'libraries': ['numpy-atlas'], 'library_dirs': ['C:\\projects\\windows-wheel-builder\\atlas-builds\\atlas-3.10.1-sse2-32\\lib'], 'language': 'c', 'define_macros': [('HAVE_CBLAS', None), ('NO_ATLAS_INFO', -1)]}
6: lapack_opt_info={'libraries': ['numpy-atlas', 'numpy-atlas'], 'library_dirs': ['C:\\projects\\windows-wheel-builder\\atlas-builds\\atlas-3.10.1-sse2-32\\lib'], 'language': 'f77', 'define_macros': [('NO_ATLAS_INFO', -1)]}
7: blas_opt_info={'libraries': ['numpy-atlas'], 'library_dirs': ['C:\\projects\\windows-wheel-builder\\atlas-builds\\atlas-3.10.1-sse2-32\\lib'], 'language': 'c', 'define_macros': [('HAVE_CBLAS', None), ('NO_ATLAS_INFO', -1)]}
8: openblas_info={}
9: openblas_lapack_info={}
10: atlas_3_10_threads_info={'libraries': ['numpy-atlas', 'numpy-atlas'], 'library_dirs': ['C:\\projects\\windows-wheel-builder\\atlas-builds\\atlas-3.10.1-sse2-32\\lib'], 'language': 'f77', 'define_macros': [('NO_ATLAS_INFO', -1)]}
11: lapack_mkl_info={}
12: blas_mkl_info={}
13: mkl_info={}
14: 
15: def get_info(name):
16:     g = globals()
17:     return g.get(name, g.get(name + "_info", {}))
18: 
19: def show():
20:     for name,info_dict in globals().items():
21:         if name[0] == "_" or type(info_dict) is not type({}): continue
22:         print(name + ":")
23:         if not info_dict:
24:             print("  NOT AVAILABLE")
25:         for k,v in info_dict.items():
26:             v = str(v)
27:             if k == "sources" and len(v) > 200:
28:                 v = v[:60] + " ...\n... " + v[-60:]
29:             print("    %s = %s" % (k,v))
30:     

"""

# Import the stypy library necessary elements
from stypy.type_inference_programs.type_inference_programs_imports import *

# Create the module type store
module_type_store = Context(None, __file__)

# ################# Begin of the type inference program ##################


# Assigning a List to a Name (line 3):
__all__ = ['get_info', 'show']
module_type_store.set_exportable_members(['get_info', 'show'])

# Obtaining an instance of the builtin type 'list' (line 3)
list_52093 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 3, 10), 'list')
# Adding type elements to the builtin type 'list' instance (line 3)
# Adding element type (line 3)
str_52094 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 3, 11), 'str', 'get_info')
add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 3, 10), list_52093, str_52094)
# Adding element type (line 3)
str_52095 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 3, 22), 'str', 'show')
add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 3, 10), list_52093, str_52095)

# Assigning a type to the variable '__all__' (line 3)
module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 3, 0), '__all__', list_52093)

# Assigning a Dict to a Name (line 5):

# Obtaining an instance of the builtin type 'dict' (line 5)
dict_52096 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 5, 29), 'dict')
# Adding type elements to the builtin type 'dict' instance (line 5)
# Adding element type (key, value) (line 5)
str_52097 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 5, 30), 'str', 'libraries')

# Obtaining an instance of the builtin type 'list' (line 5)
list_52098 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 5, 43), 'list')
# Adding type elements to the builtin type 'list' instance (line 5)
# Adding element type (line 5)
str_52099 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 5, 44), 'str', 'numpy-atlas')
add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 5, 43), list_52098, str_52099)

set_contained_elements_type(stypy.reporting.localization.Localization(__file__, 5, 29), dict_52096, (str_52097, list_52098))
# Adding element type (key, value) (line 5)
str_52100 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 5, 60), 'str', 'library_dirs')

# Obtaining an instance of the builtin type 'list' (line 5)
list_52101 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 5, 76), 'list')
# Adding type elements to the builtin type 'list' instance (line 5)
# Adding element type (line 5)
str_52102 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 5, 77), 'str', 'C:\\projects\\windows-wheel-builder\\atlas-builds\\atlas-3.10.1-sse2-32\\lib')
add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 5, 76), list_52101, str_52102)

set_contained_elements_type(stypy.reporting.localization.Localization(__file__, 5, 29), dict_52096, (str_52100, list_52101))
# Adding element type (key, value) (line 5)
str_52103 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 5, 158), 'str', 'language')
str_52104 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 5, 170), 'str', 'c')
set_contained_elements_type(stypy.reporting.localization.Localization(__file__, 5, 29), dict_52096, (str_52103, str_52104))
# Adding element type (key, value) (line 5)
str_52105 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 5, 175), 'str', 'define_macros')

# Obtaining an instance of the builtin type 'list' (line 5)
list_52106 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 5, 192), 'list')
# Adding type elements to the builtin type 'list' instance (line 5)
# Adding element type (line 5)

# Obtaining an instance of the builtin type 'tuple' (line 5)
tuple_52107 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 5, 194), 'tuple')
# Adding type elements to the builtin type 'tuple' instance (line 5)
# Adding element type (line 5)
str_52108 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 5, 194), 'str', 'HAVE_CBLAS')
add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 5, 194), tuple_52107, str_52108)
# Adding element type (line 5)
# Getting the type of 'None' (line 5)
None_52109 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 5, 208), 'None')
add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 5, 194), tuple_52107, None_52109)

add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 5, 192), list_52106, tuple_52107)
# Adding element type (line 5)

# Obtaining an instance of the builtin type 'tuple' (line 5)
tuple_52110 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 5, 216), 'tuple')
# Adding type elements to the builtin type 'tuple' instance (line 5)
# Adding element type (line 5)
str_52111 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 5, 216), 'str', 'NO_ATLAS_INFO')
add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 5, 216), tuple_52110, str_52111)
# Adding element type (line 5)
int_52112 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 5, 233), 'int')
add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 5, 216), tuple_52110, int_52112)

add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 5, 192), list_52106, tuple_52110)

set_contained_elements_type(stypy.reporting.localization.Localization(__file__, 5, 29), dict_52096, (str_52105, list_52106))

# Assigning a type to the variable 'atlas_3_10_blas_threads_info' (line 5)
module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 5, 0), 'atlas_3_10_blas_threads_info', dict_52096)

# Assigning a Dict to a Name (line 6):

# Obtaining an instance of the builtin type 'dict' (line 6)
dict_52113 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 6, 16), 'dict')
# Adding type elements to the builtin type 'dict' instance (line 6)
# Adding element type (key, value) (line 6)
str_52114 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 6, 17), 'str', 'libraries')

# Obtaining an instance of the builtin type 'list' (line 6)
list_52115 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 6, 30), 'list')
# Adding type elements to the builtin type 'list' instance (line 6)
# Adding element type (line 6)
str_52116 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 6, 31), 'str', 'numpy-atlas')
add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 6, 30), list_52115, str_52116)
# Adding element type (line 6)
str_52117 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 6, 46), 'str', 'numpy-atlas')
add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 6, 30), list_52115, str_52117)

set_contained_elements_type(stypy.reporting.localization.Localization(__file__, 6, 16), dict_52113, (str_52114, list_52115))
# Adding element type (key, value) (line 6)
str_52118 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 6, 62), 'str', 'library_dirs')

# Obtaining an instance of the builtin type 'list' (line 6)
list_52119 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 6, 78), 'list')
# Adding type elements to the builtin type 'list' instance (line 6)
# Adding element type (line 6)
str_52120 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 6, 79), 'str', 'C:\\projects\\windows-wheel-builder\\atlas-builds\\atlas-3.10.1-sse2-32\\lib')
add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 6, 78), list_52119, str_52120)

set_contained_elements_type(stypy.reporting.localization.Localization(__file__, 6, 16), dict_52113, (str_52118, list_52119))
# Adding element type (key, value) (line 6)
str_52121 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 6, 160), 'str', 'language')
str_52122 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 6, 172), 'str', 'f77')
set_contained_elements_type(stypy.reporting.localization.Localization(__file__, 6, 16), dict_52113, (str_52121, str_52122))
# Adding element type (key, value) (line 6)
str_52123 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 6, 179), 'str', 'define_macros')

# Obtaining an instance of the builtin type 'list' (line 6)
list_52124 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 6, 196), 'list')
# Adding type elements to the builtin type 'list' instance (line 6)
# Adding element type (line 6)

# Obtaining an instance of the builtin type 'tuple' (line 6)
tuple_52125 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 6, 198), 'tuple')
# Adding type elements to the builtin type 'tuple' instance (line 6)
# Adding element type (line 6)
str_52126 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 6, 198), 'str', 'NO_ATLAS_INFO')
add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 6, 198), tuple_52125, str_52126)
# Adding element type (line 6)
int_52127 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 6, 215), 'int')
add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 6, 198), tuple_52125, int_52127)

add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 6, 196), list_52124, tuple_52125)

set_contained_elements_type(stypy.reporting.localization.Localization(__file__, 6, 16), dict_52113, (str_52123, list_52124))

# Assigning a type to the variable 'lapack_opt_info' (line 6)
module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 6, 0), 'lapack_opt_info', dict_52113)

# Assigning a Dict to a Name (line 7):

# Obtaining an instance of the builtin type 'dict' (line 7)
dict_52128 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 7, 14), 'dict')
# Adding type elements to the builtin type 'dict' instance (line 7)
# Adding element type (key, value) (line 7)
str_52129 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 7, 15), 'str', 'libraries')

# Obtaining an instance of the builtin type 'list' (line 7)
list_52130 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 7, 28), 'list')
# Adding type elements to the builtin type 'list' instance (line 7)
# Adding element type (line 7)
str_52131 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 7, 29), 'str', 'numpy-atlas')
add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 7, 28), list_52130, str_52131)

set_contained_elements_type(stypy.reporting.localization.Localization(__file__, 7, 14), dict_52128, (str_52129, list_52130))
# Adding element type (key, value) (line 7)
str_52132 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 7, 45), 'str', 'library_dirs')

# Obtaining an instance of the builtin type 'list' (line 7)
list_52133 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 7, 61), 'list')
# Adding type elements to the builtin type 'list' instance (line 7)
# Adding element type (line 7)
str_52134 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 7, 62), 'str', 'C:\\projects\\windows-wheel-builder\\atlas-builds\\atlas-3.10.1-sse2-32\\lib')
add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 7, 61), list_52133, str_52134)

set_contained_elements_type(stypy.reporting.localization.Localization(__file__, 7, 14), dict_52128, (str_52132, list_52133))
# Adding element type (key, value) (line 7)
str_52135 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 7, 143), 'str', 'language')
str_52136 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 7, 155), 'str', 'c')
set_contained_elements_type(stypy.reporting.localization.Localization(__file__, 7, 14), dict_52128, (str_52135, str_52136))
# Adding element type (key, value) (line 7)
str_52137 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 7, 160), 'str', 'define_macros')

# Obtaining an instance of the builtin type 'list' (line 7)
list_52138 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 7, 177), 'list')
# Adding type elements to the builtin type 'list' instance (line 7)
# Adding element type (line 7)

# Obtaining an instance of the builtin type 'tuple' (line 7)
tuple_52139 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 7, 179), 'tuple')
# Adding type elements to the builtin type 'tuple' instance (line 7)
# Adding element type (line 7)
str_52140 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 7, 179), 'str', 'HAVE_CBLAS')
add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 7, 179), tuple_52139, str_52140)
# Adding element type (line 7)
# Getting the type of 'None' (line 7)
None_52141 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 7, 193), 'None')
add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 7, 179), tuple_52139, None_52141)

add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 7, 177), list_52138, tuple_52139)
# Adding element type (line 7)

# Obtaining an instance of the builtin type 'tuple' (line 7)
tuple_52142 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 7, 201), 'tuple')
# Adding type elements to the builtin type 'tuple' instance (line 7)
# Adding element type (line 7)
str_52143 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 7, 201), 'str', 'NO_ATLAS_INFO')
add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 7, 201), tuple_52142, str_52143)
# Adding element type (line 7)
int_52144 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 7, 218), 'int')
add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 7, 201), tuple_52142, int_52144)

add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 7, 177), list_52138, tuple_52142)

set_contained_elements_type(stypy.reporting.localization.Localization(__file__, 7, 14), dict_52128, (str_52137, list_52138))

# Assigning a type to the variable 'blas_opt_info' (line 7)
module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 7, 0), 'blas_opt_info', dict_52128)

# Assigning a Dict to a Name (line 8):

# Obtaining an instance of the builtin type 'dict' (line 8)
dict_52145 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 8, 14), 'dict')
# Adding type elements to the builtin type 'dict' instance (line 8)

# Assigning a type to the variable 'openblas_info' (line 8)
module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 8, 0), 'openblas_info', dict_52145)

# Assigning a Dict to a Name (line 9):

# Obtaining an instance of the builtin type 'dict' (line 9)
dict_52146 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 9, 21), 'dict')
# Adding type elements to the builtin type 'dict' instance (line 9)

# Assigning a type to the variable 'openblas_lapack_info' (line 9)
module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 9, 0), 'openblas_lapack_info', dict_52146)

# Assigning a Dict to a Name (line 10):

# Obtaining an instance of the builtin type 'dict' (line 10)
dict_52147 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 10, 24), 'dict')
# Adding type elements to the builtin type 'dict' instance (line 10)
# Adding element type (key, value) (line 10)
str_52148 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 10, 25), 'str', 'libraries')

# Obtaining an instance of the builtin type 'list' (line 10)
list_52149 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 10, 38), 'list')
# Adding type elements to the builtin type 'list' instance (line 10)
# Adding element type (line 10)
str_52150 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 10, 39), 'str', 'numpy-atlas')
add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 10, 38), list_52149, str_52150)
# Adding element type (line 10)
str_52151 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 10, 54), 'str', 'numpy-atlas')
add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 10, 38), list_52149, str_52151)

set_contained_elements_type(stypy.reporting.localization.Localization(__file__, 10, 24), dict_52147, (str_52148, list_52149))
# Adding element type (key, value) (line 10)
str_52152 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 10, 70), 'str', 'library_dirs')

# Obtaining an instance of the builtin type 'list' (line 10)
list_52153 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 10, 86), 'list')
# Adding type elements to the builtin type 'list' instance (line 10)
# Adding element type (line 10)
str_52154 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 10, 87), 'str', 'C:\\projects\\windows-wheel-builder\\atlas-builds\\atlas-3.10.1-sse2-32\\lib')
add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 10, 86), list_52153, str_52154)

set_contained_elements_type(stypy.reporting.localization.Localization(__file__, 10, 24), dict_52147, (str_52152, list_52153))
# Adding element type (key, value) (line 10)
str_52155 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 10, 168), 'str', 'language')
str_52156 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 10, 180), 'str', 'f77')
set_contained_elements_type(stypy.reporting.localization.Localization(__file__, 10, 24), dict_52147, (str_52155, str_52156))
# Adding element type (key, value) (line 10)
str_52157 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 10, 187), 'str', 'define_macros')

# Obtaining an instance of the builtin type 'list' (line 10)
list_52158 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 10, 204), 'list')
# Adding type elements to the builtin type 'list' instance (line 10)
# Adding element type (line 10)

# Obtaining an instance of the builtin type 'tuple' (line 10)
tuple_52159 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 10, 206), 'tuple')
# Adding type elements to the builtin type 'tuple' instance (line 10)
# Adding element type (line 10)
str_52160 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 10, 206), 'str', 'NO_ATLAS_INFO')
add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 10, 206), tuple_52159, str_52160)
# Adding element type (line 10)
int_52161 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 10, 223), 'int')
add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 10, 206), tuple_52159, int_52161)

add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 10, 204), list_52158, tuple_52159)

set_contained_elements_type(stypy.reporting.localization.Localization(__file__, 10, 24), dict_52147, (str_52157, list_52158))

# Assigning a type to the variable 'atlas_3_10_threads_info' (line 10)
module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 10, 0), 'atlas_3_10_threads_info', dict_52147)

# Assigning a Dict to a Name (line 11):

# Obtaining an instance of the builtin type 'dict' (line 11)
dict_52162 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 11, 16), 'dict')
# Adding type elements to the builtin type 'dict' instance (line 11)

# Assigning a type to the variable 'lapack_mkl_info' (line 11)
module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 11, 0), 'lapack_mkl_info', dict_52162)

# Assigning a Dict to a Name (line 12):

# Obtaining an instance of the builtin type 'dict' (line 12)
dict_52163 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 12, 14), 'dict')
# Adding type elements to the builtin type 'dict' instance (line 12)

# Assigning a type to the variable 'blas_mkl_info' (line 12)
module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 12, 0), 'blas_mkl_info', dict_52163)

# Assigning a Dict to a Name (line 13):

# Obtaining an instance of the builtin type 'dict' (line 13)
dict_52164 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 13, 9), 'dict')
# Adding type elements to the builtin type 'dict' instance (line 13)

# Assigning a type to the variable 'mkl_info' (line 13)
module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 13, 0), 'mkl_info', dict_52164)

@norecursion
def get_info(localization, *varargs, **kwargs):
    global module_type_store
    # Assign values to the parameters with defaults
    defaults = []
    # Create a new context for function 'get_info'
    module_type_store = module_type_store.open_function_context('get_info', 15, 0, False)
    
    # Passed parameters checking function
    get_info.stypy_localization = localization
    get_info.stypy_type_of_self = None
    get_info.stypy_type_store = module_type_store
    get_info.stypy_function_name = 'get_info'
    get_info.stypy_param_names_list = ['name']
    get_info.stypy_varargs_param_name = None
    get_info.stypy_kwargs_param_name = None
    get_info.stypy_call_defaults = defaults
    get_info.stypy_call_varargs = varargs
    get_info.stypy_call_kwargs = kwargs
    arguments = process_argument_values(localization, None, module_type_store, 'get_info', ['name'], None, None, defaults, varargs, kwargs)

    if is_error_type(arguments):
        # Destroy the current context
        module_type_store = module_type_store.close_function_context()
        return arguments

    # Initialize method data
    init_call_information(module_type_store, 'get_info', localization, ['name'], arguments)
    
    # Default return type storage variable (SSA)
    # Assigning a type to the variable 'stypy_return_type'
    module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 0, 0), 'stypy_return_type', None)
    
    
    # ################# Begin of 'get_info(...)' code ##################

    
    # Assigning a Call to a Name (line 16):
    
    # Call to globals(...): (line 16)
    # Processing the call keyword arguments (line 16)
    kwargs_52166 = {}
    # Getting the type of 'globals' (line 16)
    globals_52165 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 16, 8), 'globals', False)
    # Calling globals(args, kwargs) (line 16)
    globals_call_result_52167 = invoke(stypy.reporting.localization.Localization(__file__, 16, 8), globals_52165, *[], **kwargs_52166)
    
    # Assigning a type to the variable 'g' (line 16)
    module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 16, 4), 'g', globals_call_result_52167)
    
    # Call to get(...): (line 17)
    # Processing the call arguments (line 17)
    # Getting the type of 'name' (line 17)
    name_52170 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 17, 17), 'name', False)
    
    # Call to get(...): (line 17)
    # Processing the call arguments (line 17)
    # Getting the type of 'name' (line 17)
    name_52173 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 17, 29), 'name', False)
    str_52174 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 17, 36), 'str', '_info')
    # Applying the binary operator '+' (line 17)
    result_add_52175 = python_operator(stypy.reporting.localization.Localization(__file__, 17, 29), '+', name_52173, str_52174)
    
    
    # Obtaining an instance of the builtin type 'dict' (line 17)
    dict_52176 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 17, 45), 'dict')
    # Adding type elements to the builtin type 'dict' instance (line 17)
    
    # Processing the call keyword arguments (line 17)
    kwargs_52177 = {}
    # Getting the type of 'g' (line 17)
    g_52171 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 17, 23), 'g', False)
    # Obtaining the member 'get' of a type (line 17)
    get_52172 = module_type_store.get_type_of_member(stypy.reporting.localization.Localization(__file__, 17, 23), g_52171, 'get')
    # Calling get(args, kwargs) (line 17)
    get_call_result_52178 = invoke(stypy.reporting.localization.Localization(__file__, 17, 23), get_52172, *[result_add_52175, dict_52176], **kwargs_52177)
    
    # Processing the call keyword arguments (line 17)
    kwargs_52179 = {}
    # Getting the type of 'g' (line 17)
    g_52168 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 17, 11), 'g', False)
    # Obtaining the member 'get' of a type (line 17)
    get_52169 = module_type_store.get_type_of_member(stypy.reporting.localization.Localization(__file__, 17, 11), g_52168, 'get')
    # Calling get(args, kwargs) (line 17)
    get_call_result_52180 = invoke(stypy.reporting.localization.Localization(__file__, 17, 11), get_52169, *[name_52170, get_call_result_52178], **kwargs_52179)
    
    # Assigning a type to the variable 'stypy_return_type' (line 17)
    module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 17, 4), 'stypy_return_type', get_call_result_52180)
    
    # ################# End of 'get_info(...)' code ##################

    # Teardown call information
    teardown_call_information(localization, arguments)
    
    # Storing the return type of function 'get_info' in the type store
    # Getting the type of 'stypy_return_type' (line 15)
    stypy_return_type_52181 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 15, 0), 'stypy_return_type')
    module_type_store.store_return_type_of_current_context(stypy_return_type_52181)
    
    # Destroy the current context
    module_type_store = module_type_store.close_function_context()
    
    # Return type of the function 'get_info'
    return stypy_return_type_52181

# Assigning a type to the variable 'get_info' (line 15)
module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 15, 0), 'get_info', get_info)

@norecursion
def show(localization, *varargs, **kwargs):
    global module_type_store
    # Assign values to the parameters with defaults
    defaults = []
    # Create a new context for function 'show'
    module_type_store = module_type_store.open_function_context('show', 19, 0, False)
    
    # Passed parameters checking function
    show.stypy_localization = localization
    show.stypy_type_of_self = None
    show.stypy_type_store = module_type_store
    show.stypy_function_name = 'show'
    show.stypy_param_names_list = []
    show.stypy_varargs_param_name = None
    show.stypy_kwargs_param_name = None
    show.stypy_call_defaults = defaults
    show.stypy_call_varargs = varargs
    show.stypy_call_kwargs = kwargs
    arguments = process_argument_values(localization, None, module_type_store, 'show', [], None, None, defaults, varargs, kwargs)

    if is_error_type(arguments):
        # Destroy the current context
        module_type_store = module_type_store.close_function_context()
        return arguments

    # Initialize method data
    init_call_information(module_type_store, 'show', localization, [], arguments)
    
    # Default return type storage variable (SSA)
    # Assigning a type to the variable 'stypy_return_type'
    module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 0, 0), 'stypy_return_type', None)
    
    
    # ################# Begin of 'show(...)' code ##################

    
    
    # Call to items(...): (line 20)
    # Processing the call keyword arguments (line 20)
    kwargs_52186 = {}
    
    # Call to globals(...): (line 20)
    # Processing the call keyword arguments (line 20)
    kwargs_52183 = {}
    # Getting the type of 'globals' (line 20)
    globals_52182 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 20, 26), 'globals', False)
    # Calling globals(args, kwargs) (line 20)
    globals_call_result_52184 = invoke(stypy.reporting.localization.Localization(__file__, 20, 26), globals_52182, *[], **kwargs_52183)
    
    # Obtaining the member 'items' of a type (line 20)
    items_52185 = module_type_store.get_type_of_member(stypy.reporting.localization.Localization(__file__, 20, 26), globals_call_result_52184, 'items')
    # Calling items(args, kwargs) (line 20)
    items_call_result_52187 = invoke(stypy.reporting.localization.Localization(__file__, 20, 26), items_52185, *[], **kwargs_52186)
    
    # Testing the type of a for loop iterable (line 20)
    is_suitable_for_loop_condition(stypy.reporting.localization.Localization(__file__, 20, 4), items_call_result_52187)
    # Getting the type of the for loop variable (line 20)
    for_loop_var_52188 = get_type_of_for_loop_variable(stypy.reporting.localization.Localization(__file__, 20, 4), items_call_result_52187)
    # Assigning a type to the variable 'name' (line 20)
    module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 20, 4), 'name', get_contained_elements_type(stypy.reporting.localization.Localization(__file__, 20, 4), for_loop_var_52188))
    # Assigning a type to the variable 'info_dict' (line 20)
    module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 20, 4), 'info_dict', get_contained_elements_type(stypy.reporting.localization.Localization(__file__, 20, 4), for_loop_var_52188))
    # SSA begins for a for statement (line 20)
    module_type_store = SSAContext.create_ssa_context(module_type_store, 'for loop')
    
    
    # Evaluating a boolean operation
    
    
    # Obtaining the type of the subscript
    int_52189 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 21, 16), 'int')
    # Getting the type of 'name' (line 21)
    name_52190 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 21, 11), 'name')
    # Obtaining the member '__getitem__' of a type (line 21)
    getitem___52191 = module_type_store.get_type_of_member(stypy.reporting.localization.Localization(__file__, 21, 11), name_52190, '__getitem__')
    # Calling the subscript (__getitem__) to obtain the elements type (line 21)
    subscript_call_result_52192 = invoke(stypy.reporting.localization.Localization(__file__, 21, 11), getitem___52191, int_52189)
    
    str_52193 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 21, 22), 'str', '_')
    # Applying the binary operator '==' (line 21)
    result_eq_52194 = python_operator(stypy.reporting.localization.Localization(__file__, 21, 11), '==', subscript_call_result_52192, str_52193)
    
    
    
    # Call to type(...): (line 21)
    # Processing the call arguments (line 21)
    # Getting the type of 'info_dict' (line 21)
    info_dict_52196 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 21, 34), 'info_dict', False)
    # Processing the call keyword arguments (line 21)
    kwargs_52197 = {}
    # Getting the type of 'type' (line 21)
    type_52195 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 21, 29), 'type', False)
    # Calling type(args, kwargs) (line 21)
    type_call_result_52198 = invoke(stypy.reporting.localization.Localization(__file__, 21, 29), type_52195, *[info_dict_52196], **kwargs_52197)
    
    
    # Call to type(...): (line 21)
    # Processing the call arguments (line 21)
    
    # Obtaining an instance of the builtin type 'dict' (line 21)
    dict_52200 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 21, 57), 'dict')
    # Adding type elements to the builtin type 'dict' instance (line 21)
    
    # Processing the call keyword arguments (line 21)
    kwargs_52201 = {}
    # Getting the type of 'type' (line 21)
    type_52199 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 21, 52), 'type', False)
    # Calling type(args, kwargs) (line 21)
    type_call_result_52202 = invoke(stypy.reporting.localization.Localization(__file__, 21, 52), type_52199, *[dict_52200], **kwargs_52201)
    
    # Applying the binary operator 'isnot' (line 21)
    result_is_not_52203 = python_operator(stypy.reporting.localization.Localization(__file__, 21, 29), 'isnot', type_call_result_52198, type_call_result_52202)
    
    # Applying the binary operator 'or' (line 21)
    result_or_keyword_52204 = python_operator(stypy.reporting.localization.Localization(__file__, 21, 11), 'or', result_eq_52194, result_is_not_52203)
    
    # Testing the type of an if condition (line 21)
    if_condition_52205 = is_suitable_condition(stypy.reporting.localization.Localization(__file__, 21, 8), result_or_keyword_52204)
    # Assigning a type to the variable 'if_condition_52205' (line 21)
    module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 21, 8), 'if_condition_52205', if_condition_52205)
    # SSA begins for if statement (line 21)
    module_type_store = SSAContext.create_ssa_context(module_type_store, 'if')
    # SSA join for if statement (line 21)
    module_type_store = module_type_store.join_ssa_context()
    
    # Getting the type of 'name' (line 22)
    name_52206 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 22, 14), 'name')
    str_52207 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 22, 21), 'str', ':')
    # Applying the binary operator '+' (line 22)
    result_add_52208 = python_operator(stypy.reporting.localization.Localization(__file__, 22, 14), '+', name_52206, str_52207)
    
    
    
    # Getting the type of 'info_dict' (line 23)
    info_dict_52209 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 23, 15), 'info_dict')
    # Applying the 'not' unary operator (line 23)
    result_not__52210 = python_operator(stypy.reporting.localization.Localization(__file__, 23, 11), 'not', info_dict_52209)
    
    # Testing the type of an if condition (line 23)
    if_condition_52211 = is_suitable_condition(stypy.reporting.localization.Localization(__file__, 23, 8), result_not__52210)
    # Assigning a type to the variable 'if_condition_52211' (line 23)
    module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 23, 8), 'if_condition_52211', if_condition_52211)
    # SSA begins for if statement (line 23)
    module_type_store = SSAContext.create_ssa_context(module_type_store, 'if')
    str_52212 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 24, 18), 'str', '  NOT AVAILABLE')
    # SSA join for if statement (line 23)
    module_type_store = module_type_store.join_ssa_context()
    
    
    
    # Call to items(...): (line 25)
    # Processing the call keyword arguments (line 25)
    kwargs_52215 = {}
    # Getting the type of 'info_dict' (line 25)
    info_dict_52213 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 25, 19), 'info_dict', False)
    # Obtaining the member 'items' of a type (line 25)
    items_52214 = module_type_store.get_type_of_member(stypy.reporting.localization.Localization(__file__, 25, 19), info_dict_52213, 'items')
    # Calling items(args, kwargs) (line 25)
    items_call_result_52216 = invoke(stypy.reporting.localization.Localization(__file__, 25, 19), items_52214, *[], **kwargs_52215)
    
    # Testing the type of a for loop iterable (line 25)
    is_suitable_for_loop_condition(stypy.reporting.localization.Localization(__file__, 25, 8), items_call_result_52216)
    # Getting the type of the for loop variable (line 25)
    for_loop_var_52217 = get_type_of_for_loop_variable(stypy.reporting.localization.Localization(__file__, 25, 8), items_call_result_52216)
    # Assigning a type to the variable 'k' (line 25)
    module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 25, 8), 'k', get_contained_elements_type(stypy.reporting.localization.Localization(__file__, 25, 8), for_loop_var_52217))
    # Assigning a type to the variable 'v' (line 25)
    module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 25, 8), 'v', get_contained_elements_type(stypy.reporting.localization.Localization(__file__, 25, 8), for_loop_var_52217))
    # SSA begins for a for statement (line 25)
    module_type_store = SSAContext.create_ssa_context(module_type_store, 'for loop')
    
    # Assigning a Call to a Name (line 26):
    
    # Call to str(...): (line 26)
    # Processing the call arguments (line 26)
    # Getting the type of 'v' (line 26)
    v_52219 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 26, 20), 'v', False)
    # Processing the call keyword arguments (line 26)
    kwargs_52220 = {}
    # Getting the type of 'str' (line 26)
    str_52218 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 26, 16), 'str', False)
    # Calling str(args, kwargs) (line 26)
    str_call_result_52221 = invoke(stypy.reporting.localization.Localization(__file__, 26, 16), str_52218, *[v_52219], **kwargs_52220)
    
    # Assigning a type to the variable 'v' (line 26)
    module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 26, 12), 'v', str_call_result_52221)
    
    
    # Evaluating a boolean operation
    
    # Getting the type of 'k' (line 27)
    k_52222 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 27, 15), 'k')
    str_52223 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 27, 20), 'str', 'sources')
    # Applying the binary operator '==' (line 27)
    result_eq_52224 = python_operator(stypy.reporting.localization.Localization(__file__, 27, 15), '==', k_52222, str_52223)
    
    
    
    # Call to len(...): (line 27)
    # Processing the call arguments (line 27)
    # Getting the type of 'v' (line 27)
    v_52226 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 27, 38), 'v', False)
    # Processing the call keyword arguments (line 27)
    kwargs_52227 = {}
    # Getting the type of 'len' (line 27)
    len_52225 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 27, 34), 'len', False)
    # Calling len(args, kwargs) (line 27)
    len_call_result_52228 = invoke(stypy.reporting.localization.Localization(__file__, 27, 34), len_52225, *[v_52226], **kwargs_52227)
    
    int_52229 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 27, 43), 'int')
    # Applying the binary operator '>' (line 27)
    result_gt_52230 = python_operator(stypy.reporting.localization.Localization(__file__, 27, 34), '>', len_call_result_52228, int_52229)
    
    # Applying the binary operator 'and' (line 27)
    result_and_keyword_52231 = python_operator(stypy.reporting.localization.Localization(__file__, 27, 15), 'and', result_eq_52224, result_gt_52230)
    
    # Testing the type of an if condition (line 27)
    if_condition_52232 = is_suitable_condition(stypy.reporting.localization.Localization(__file__, 27, 12), result_and_keyword_52231)
    # Assigning a type to the variable 'if_condition_52232' (line 27)
    module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 27, 12), 'if_condition_52232', if_condition_52232)
    # SSA begins for if statement (line 27)
    module_type_store = SSAContext.create_ssa_context(module_type_store, 'if')
    
    # Assigning a BinOp to a Name (line 28):
    
    # Obtaining the type of the subscript
    int_52233 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 28, 23), 'int')
    slice_52234 = ensure_slice_bounds(stypy.reporting.localization.Localization(__file__, 28, 20), None, int_52233, None)
    # Getting the type of 'v' (line 28)
    v_52235 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 28, 20), 'v')
    # Obtaining the member '__getitem__' of a type (line 28)
    getitem___52236 = module_type_store.get_type_of_member(stypy.reporting.localization.Localization(__file__, 28, 20), v_52235, '__getitem__')
    # Calling the subscript (__getitem__) to obtain the elements type (line 28)
    subscript_call_result_52237 = invoke(stypy.reporting.localization.Localization(__file__, 28, 20), getitem___52236, slice_52234)
    
    str_52238 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 28, 29), 'str', ' ...\n... ')
    # Applying the binary operator '+' (line 28)
    result_add_52239 = python_operator(stypy.reporting.localization.Localization(__file__, 28, 20), '+', subscript_call_result_52237, str_52238)
    
    
    # Obtaining the type of the subscript
    int_52240 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 28, 46), 'int')
    slice_52241 = ensure_slice_bounds(stypy.reporting.localization.Localization(__file__, 28, 44), int_52240, None, None)
    # Getting the type of 'v' (line 28)
    v_52242 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 28, 44), 'v')
    # Obtaining the member '__getitem__' of a type (line 28)
    getitem___52243 = module_type_store.get_type_of_member(stypy.reporting.localization.Localization(__file__, 28, 44), v_52242, '__getitem__')
    # Calling the subscript (__getitem__) to obtain the elements type (line 28)
    subscript_call_result_52244 = invoke(stypy.reporting.localization.Localization(__file__, 28, 44), getitem___52243, slice_52241)
    
    # Applying the binary operator '+' (line 28)
    result_add_52245 = python_operator(stypy.reporting.localization.Localization(__file__, 28, 42), '+', result_add_52239, subscript_call_result_52244)
    
    # Assigning a type to the variable 'v' (line 28)
    module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 28, 16), 'v', result_add_52245)
    # SSA join for if statement (line 27)
    module_type_store = module_type_store.join_ssa_context()
    
    str_52246 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 29, 18), 'str', '    %s = %s')
    
    # Obtaining an instance of the builtin type 'tuple' (line 29)
    tuple_52247 = get_builtin_python_type_instance(stypy.reporting.localization.Localization(__file__, 29, 35), 'tuple')
    # Adding type elements to the builtin type 'tuple' instance (line 29)
    # Adding element type (line 29)
    # Getting the type of 'k' (line 29)
    k_52248 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 29, 35), 'k')
    add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 29, 35), tuple_52247, k_52248)
    # Adding element type (line 29)
    # Getting the type of 'v' (line 29)
    v_52249 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 29, 37), 'v')
    add_contained_elements_type(stypy.reporting.localization.Localization(__file__, 29, 35), tuple_52247, v_52249)
    
    # Applying the binary operator '%' (line 29)
    result_mod_52250 = python_operator(stypy.reporting.localization.Localization(__file__, 29, 18), '%', str_52246, tuple_52247)
    
    # SSA join for a for statement
    module_type_store = module_type_store.join_ssa_context()
    
    # SSA join for a for statement
    module_type_store = module_type_store.join_ssa_context()
    
    
    # ################# End of 'show(...)' code ##################

    # Teardown call information
    teardown_call_information(localization, arguments)
    
    # Storing the return type of function 'show' in the type store
    # Getting the type of 'stypy_return_type' (line 19)
    stypy_return_type_52251 = module_type_store.get_type_of(stypy.reporting.localization.Localization(__file__, 19, 0), 'stypy_return_type')
    module_type_store.store_return_type_of_current_context(stypy_return_type_52251)
    
    # Destroy the current context
    module_type_store = module_type_store.close_function_context()
    
    # Return type of the function 'show'
    return stypy_return_type_52251

# Assigning a type to the variable 'show' (line 19)
module_type_store.set_type_of(stypy.reporting.localization.Localization(__file__, 19, 0), 'show', show)

# ################# End of the type inference program ##################

module_errors = stypy.errors.type_error.StypyTypeError.get_error_msgs()
module_warnings = stypy.errors.type_warning.TypeWarning.get_warning_msgs()
