from testing.code_generation_testing.codegen_testing_common import instance_of_class_name
import numpy
from stypy.types.union_type import UnionType
from stypy.invokation.type_rules.type_groups.type_groups import DynamicType

test_types = {
    '__main__': {
        'b2': instance_of_class_name("ndarray"),
        'a': instance_of_class_name("ndarray"),
        'r28': instance_of_class_name("ndarray"),
        'r29': UnionType.create_from_type_list([numpy.int32, numpy.ndarray]),
        'b3': instance_of_class_name("ndarray"),
        'r27': UnionType.create_from_type_list([numpy.float64, numpy.ndarray]),
        'r26': UnionType.create_from_type_list([numpy.float64, numpy.ndarray]),
        'r25': instance_of_class_name("ndarray"),
        'r24': UnionType.create_from_type_list([numpy.int32, numpy.ndarray]),
        'r23': UnionType.create_from_type_list([numpy.int32, numpy.ndarray]),
        'r22': instance_of_class_name("ndarray"),
        'r21': UnionType.create_from_type_list([numpy.int32, numpy.ndarray]),
        'r20': UnionType.create_from_type_list([DynamicType, numpy.ndarray]),
        '__package__': instance_of_class_name("NoneType"),
        'np': instance_of_class_name("module"),
        'b': instance_of_class_name("ndarray"),
        '__doc__': instance_of_class_name("NoneType"),
        'r16': instance_of_class_name("ndarray"),
        'r17': UnionType.create_from_type_list([numpy.int32, numpy.ndarray]),
        'r14': UnionType.create_from_type_list([numpy.int32, numpy.ndarray]),
        'r15': UnionType.create_from_type_list([numpy.int32, numpy.ndarray]),
        'r12': UnionType.create_from_type_list([numpy.int32, numpy.ndarray]),
        'r13': instance_of_class_name("ndarray"),
        'r10': UnionType.create_from_type_list([numpy.int32, numpy.ndarray]),
        'r11': UnionType.create_from_type_list([numpy.int32, numpy.ndarray]),
        '__builtins__': instance_of_class_name("module"),
        '__file__': instance_of_class_name("str"),
        'c': instance_of_class_name("ndarray"),
        'r18': UnionType.create_from_type_list([numpy.int32, numpy.ndarray]),
        'r19': instance_of_class_name("ndarray"),
        'a3': instance_of_class_name("ndarray"),
        'a2': instance_of_class_name("ndarray"),
        'a4': instance_of_class_name("ndarray"),
        '__name__': instance_of_class_name("str"),
        'r30': UnionType.create_from_type_list([numpy.int32, numpy.ndarray]),
        'r31': UnionType.create_from_type_list([numpy.int32, numpy.ndarray]),
        'r32': instance_of_class_name("ndarray"),
        'r4': UnionType.create_from_type_list([numpy.int32, numpy.ndarray]),
        'r5': UnionType.create_from_type_list([numpy.int32, numpy.ndarray]),
        'r6': instance_of_class_name("ndarray"),
        'r7': UnionType.create_from_type_list([numpy.int32, numpy.ndarray]),
        'r2': UnionType.create_from_type_list([numpy.int32, numpy.ndarray]),
        'r3': instance_of_class_name("ndarray"),
        'r8': UnionType.create_from_type_list([numpy.int32, numpy.ndarray]),
        'r9': instance_of_class_name("ndarray"),
        'r': UnionType.create_from_type_list([numpy.int32, numpy.ndarray]),

    },
}
